# Generated by dry-cli-autocomplete in dynamic mode: every TAB asks mycli.

_mycli_complete_dynamic() {
  local line
  COMPREPLY=()
  while IFS= read -r line; do
    if [ "$line" = ":files" ]; then
      COMPREPLY+=($(compgen -f -- "${COMP_WORDS[COMP_CWORD]}"))
    elif [ -n "$line" ]; then
      COMPREPLY+=("$line")
    fi
  done < <("${COMP_WORDS[0]}" __complete -- "${COMP_WORDS[@]:1:COMP_CWORD}" 2>/dev/null)
}

_mycli_completions() {
  _mycli_complete_dynamic
}
complete -F _mycli_completions mycli
