# frozen_string_literal: true

require "dry/inflector"

module Dry
  class CLI
    module Autocomplete
      module Emitters
        # Turns a CompletionSpec into a native zsh `#compdef` script.
        #
        # This is not a bashcompinit shim. Options go through `_arguments`
        # carrying their `desc` as help text, subcommands go through
        # `_describe`, declared enum values become a `(a b c)` action, and a
        # file argument becomes `_files`. That per-option help is the thing
        # zsh users lose with a shim, and the reason this emitter exists.
        # See docs/SPECIFICATION.md §4.1.
        #
        # Shares no code with the bash emitter by design: a fourth shell
        # should be a new class here, never another branch inside one of
        # these two.
        class Zsh
          # @param spec [SpecBuilder::CompletionSpec]
          # @param fallback [Class, nil] in hybrid mode, the dynamic emitter
          #   whose function answers what this script does not know
          # @return [String]
          def self.call(spec, fallback: nil)
            new(spec, fallback:).call
          end

          def initialize(spec, fallback: nil)
            @spec = spec
            @fallback = fallback
          end

          def call
            "#{body.join("\n")}\n"
          end

          private

          attr_reader :spec, :fallback

          def body
            header_lines + path_walk_lines + unknown_word_lines + dispatch_lines + footer_lines
          end

          def header_lines
            [
              "#compdef #{spec.program_name}",
              "",
              "# Generated by dry-cli-autocomplete. Regenerate after changing commands.",
              "",
              *fallback_helper_lines,
              "#{function_name}() {",
              '  local curcontext="$curcontext" state line ret=1',
              *(fallback ? ["  local unknown=0"] : []),
              "  local -a commands",
              "  typeset -A opt_args",
              ""
            ]
          end

          # Hybrid mode only, from here to {#empty_fallback_lines}: the
          # dynamic emitter's function, defined ahead of this one.
          def fallback_helper_lines
            fallback ? [*fallback.helper_lines(spec), ""] : []
          end

          # A word this script does not know, where a subcommand could go, may
          # be a command registered after the script was generated.
          def unknown_arm_lines
            return ["      (*) break ;;"] unless fallback && group_paths.any?

            [
              "      (*)",
              '        if [[ "${words[i]}" != -* ]]; then',
              '          case "$path_key" in',
              "            (#{group_paths.map { single_quote(it) }.join('|')}) unknown=1 ;;",
              "          esac",
              "        fi",
              "        break",
              "        ;;"
            ]
          end

          # Such a word hands the whole line to the program.
          def unknown_word_lines
            return [] unless fallback

            ["  if (( unknown )); then", "    #{fallback.function_name(spec)}", "    return", "  fi", ""]
          end

          # So does a line nothing in the script completed.
          def empty_fallback_lines
            return [] unless fallback

            ["  (( ret )) && #{fallback.function_name(spec)} && ret=0"]
          end

          # The paths of every node that has subcommands.
          def group_paths
            spec.nodes.reject { it.children.empty? }.map { path_key(it.path) }
          end

          # Resolves which node the cursor sits under by consuming words the
          # registry knows, exactly as the bash emitter does. words[1] is the
          # program itself under zsh, so the scan starts at 2.
          def path_walk_lines
            lines = [
              '  local path_key="" i=2',
              "  while (( i < CURRENT )); do",
              '    case "$path_key:${words[i]}" in'
            ]
            edge_arms.each { |arm| lines << "      #{arm}" }
            lines + [
              *unknown_arm_lines,
              "    esac",
              "    (( i += 1 ))",
              "  done",
              ""
            ]
          end

          def dispatch_lines
            lines = ['  case "$path_key" in']
            spec.nodes.each { |node| lines.concat(node_arm_lines(node)) }
            lines + ["  esac", ""]
          end

          # A #compdef file dropped on $fpath is autoloaded by the completion
          # system with its own name on the function stack, and is expected to
          # do the completion. The same text sourced from a profile, which is
          # what `eval "$(mycli completion zsh)"` does, runs with no completion
          # in progress: calling the function there reaches for _describe
          # before the completion system has defined it, and zsh reports a
          # command-not-found from inside a file the user never wrote.
          #
          # Naming the function after the program, which is the convention a
          # compdef file follows anyway, lets one line tell the two apart.
          def footer_lines
            [
              *empty_fallback_lines,
              "  return ret",
              "}",
              "",
              "if [ \"$funcstack[1]\" = \"#{function_name}\" ]; then",
              "  #{function_name} \"$@\"",
              "else",
              "  compdef #{function_name} #{spec.program_name}",
              "fi"
            ]
          end

          def node_arm_lines(node)
            inner = arguments_call_lines(node) + describe_call_lines(node)
            return [] if inner.empty?

            ["    (#{single_quote(path_key(node.path))})", *inner.map { |line| "      #{line}" }, "      ;;"]
          end

          # One `_arguments` call carrying every option and positional this
          # node declares. `-s` allows clustered single-letter flags.
          def arguments_call_lines(node)
            specs = node.options.flat_map { |option| option_specs(option) } +
                    node.arguments.map { |argument| argument_spec(argument) }
            return [] if specs.empty?

            ["_arguments -s \\", *specs[0..-2].map { |s| "  #{s} \\" }, "  #{specs.last} && ret=0"]
          end

          def describe_call_lines(node)
            return [] if node.children.empty?

            entries = node.children.map do |child|
              single_quote("#{escape_describe(child)}:#{escape_describe(child_desc(node, child))}")
            end

            ["commands=(", *entries.map { |e| "  #{e}" }, ")",
             "_describe -t commands #{single_quote(describe_tag(node))} commands && ret=0"]
          end

          # Each alias gets its own spec rather than a {-f,--force} group:
          # the grouped form needs its description outside the quotes, and
          # one entry per flag is easier to read in the generated file.
          def option_specs(option)
            names = ["--#{option.name}"] + Array(option.aliases)
            names.map { |name| single_quote("#{name}#{bracketed(option.desc)}#{option_action(option)}") }
          end

          # A boolean flag takes no value. Anything else gets one field
          # naming what it wants and one supplying the completions for it.
          def option_action(option)
            return "" if option.boolean

            ":#{escape_spec(option.name)}:#{value_action(option.values)}"
          end

          # A positional takes `:message:action`, with no bracketed
          # description: zsh shows the message itself while completing, so
          # the command's own wording goes there when it has any.
          def argument_spec(argument)
            action = argument.file ? "_files" : value_action(argument.values)
            message = argument.desc.to_s.empty? ? argument.name : argument.desc
            single_quote("*:#{escape_describe(message)}:#{action}")
          end

          def value_action(values)
            return "" if values.nil? || values.empty?

            "(#{values.map { |value| escape_spec(value) }.join(' ')})"
          end

          def bracketed(desc)
            return "" if desc.nil? || desc.empty?

            "[#{escape_bracket(desc)}]"
          end

          def child_desc(node, child)
            found = spec.nodes.find { |candidate| candidate.path == node.path + [child] }
            found&.desc.to_s
          end

          def describe_tag(node)
            node.path.empty? ? "command" : "#{node.path.join(' ')} command"
          end

          def path_key(path) = path.join(" ")

          # zsh reads `]` as the end of a description and `:` as the start of
          # the next spec field, so both have to be escaped inside one.
          def escape_bracket(str) = str.to_s.gsub("\\", "\\\\\\\\").gsub("]", "\\\\]").gsub(":", "\\\\:")

          def escape_spec(str) = str.to_s.gsub("\\", "\\\\\\\\").gsub(":", "\\\\:").gsub(/([()\[\] ])/, '\\\\\1')

          def escape_describe(str) = str.to_s.gsub("\\", "\\\\\\\\").gsub(":", "\\\\:")

          def single_quote(str) = "'#{str.to_s.gsub("'", "'\\\\''")}'"

          # `_mycli`, not `_mycli_completions`: zsh autoloads a compdef file by
          # the name of the function it defines, so matching that convention is
          # what makes the footer's fpath check work.
          def function_name = "_#{shell_identifier}"

          # A program installed as `my-tool` cannot name a shell function
          # directly. See docs/SPECIFICATION.md §4.2.
          def shell_identifier
            Dry::Inflector.new.underscore(spec.program_name.to_s).gsub(/[^A-Za-z0-9_]/, "_")
          end

          def edge_arms
            spec.nodes.flat_map do |node|
              node.children.map do |child|
                "(#{single_quote("#{path_key(node.path)}:#{child}")}) " \
                  "path_key=#{single_quote(path_key(node.path + [child]))} ;;"
              end
            end
          end
        end
      end
    end
  end
end
