# frozen_string_literal: true

require "dry/inflector"

module Dry
  class CLI
    module Autocomplete
      module Emitters
        # Turns a CompletionSpec into a zsh `#compdef` script that asks the
        # program on every TAB, through its hidden `__complete` command,
        # rather than carrying every command in the script. It completes
        # commands the program registers at runtime, at the cost of starting
        # the program.
        #
        # The static emitter uses {.helper_lines} in hybrid mode, calling the
        # same function only when a command line leaves what it knows.
        class ZshDynamic
          # @param spec [SpecBuilder::CompletionSpec]
          # @return [String] the whole script
          def self.call(spec)
            new(spec).call
          end

          # @param spec [SpecBuilder::CompletionSpec]
          # @return [Array<String>] the lines defining {#function_name}
          def self.helper_lines(spec)
            new(spec).helper_lines
          end

          # @param spec [SpecBuilder::CompletionSpec]
          # @return [String] the function that asks the program
          def self.function_name(spec)
            new(spec).function_name
          end

          # @param spec [SpecBuilder::CompletionSpec]
          def initialize(spec)
            @spec = spec
          end

          # @return [String]
          def call
            lines = [
              "#compdef #{spec.program_name}",
              "",
              "# Generated by dry-cli-autocomplete in dynamic mode: every TAB asks #{spec.program_name}.",
              "",
              *helper_lines,
              "",
              "#{completion_function}() {",
              "  #{function_name}",
              "}",
              "",
              # See the static emitter's footer: this runs the function when
              # autoloaded from $fpath, and registers it when eval'd.
              "if [ \"$funcstack[1]\" = \"#{completion_function}\" ]; then",
              "  #{completion_function} \"$@\"",
              "else",
              "  compdef #{completion_function} #{spec.program_name}",
              "fi"
            ]
            "#{lines.join("\n")}\n"
          end

          # Completes from what `<program> __complete -- <words>` prints: one
          # candidate per line, and `:files` when file names fit. Returns 0
          # when it offered anything.
          #
          # @return [Array<String>]
          def helper_lines
            [
              "#{function_name}() {",
              "  local line found=1",
              "  local -a candidates",
              '  for line in ${(f)"$("${words[1]}" __complete -- "${(@)words[2,CURRENT]}" 2>/dev/null)"}; do',
              '    if [[ "$line" == ":files" ]]; then',
              "      _files && found=0",
              "    else",
              '      candidates+=("$line")',
              "    fi",
              "  done",
              "  if (( ${#candidates} )); then",
              "    compadd -a candidates && found=0",
              "  fi",
              "  return $found",
              "}"
            ]
          end

          # @return [String]
          def function_name = "_#{shell_identifier}_complete_dynamic"

          private

          attr_reader :spec

          def completion_function = "_#{shell_identifier}"

          # A program installed as `my-tool` cannot name a shell function
          # directly. See docs/SPECIFICATION.md §4.2.
          def shell_identifier
            Dry::Inflector.new.underscore(spec.program_name.to_s).gsub(/[^A-Za-z0-9_]/, "_")
          end
        end
      end
    end
  end
end
