# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"
require "timeout"
require "yard"

task :clean do
  shell("rm -rf pkg/ tmp/ coverage/ doc/ ")
end

YARD::Rake::YardocTask.new(:doc) do |t|
  t.files = %w[lib/**/*.rb - README.md LICENSE.txt]
  t.options.unshift("--title", '"dry-cli-autocomplete: shell completion for dry-cli"')
  t.after = -> { exec("open doc/index.html") } if RUBY_PLATFORM =~ /darwin/
end

RSpec::Core::RakeTask.new(:spec)

task default: :spec
